/* eslint-disable spaced-comment */
/// <reference types="nativewind/types" />

// NOTE: This file should not be edited.
// It should be committed with your source code.
// It is generated by NativeWind.
